### ISSUE TITLE
I am concerned about the scope of this project

### ISSUE THREAD

**Issue by pjohnmeyer** [sirjdt/liftoff-assignments#1]
This project seems a little ambitious for our schedule. Especially ambitious is the rather large list of things to learn. Let's discuss trimming this down, and maybe focusing on just part of it. Are you more interested in front-end or back-end development? That might help us decide.

**Comment by sirjdt** [comment]
I made some edits to the outline in an effort to amend the project for a front-end focus, but I would still like to see if I can display the objects stored in the inventory database on a chart for some JavaScript experience.

**Comment by pjohnmeyer** [comment]
Sounds good.
