### ISSUE TITLE
P3: Wireframes and user stories don't seem to align

### ISSUE THREAD

**Issue by pjohnmeyer** [sirjdt/liftoff-assignments#4]
For example, you have a login page wireframe, but no stories about user login. You have a user story about shipping schedules, but the only thing I see about shipping schedules is a link in the top-of-page navigation bar.

Do we need some additional wireframes for your MVP stories? Or are the wireframes hinting at a different list of MVP stories?

**Comment by sirjdt** [comment]
I didn't proofread the readme, I omitted the login page idea but accidentally linked that wireframe instead of the shipping page wireframe. I fixed it, apologies.

**Comment by pjohnmeyer** [comment]
Looks good now, thanks. I still think there is some misalignment but the picture is clearer now.
