### ISSUE TITLE
P3: A few of your user stories might be a little big

### ISSUE THREAD

**Issue by pjohnmeyer** [sirjdt/liftoff-assignments#5]
For example, [Users can view the Inventory on multiple pages or as a whole](https://www.pivotaltracker.com/story/show/159384005)

The "or" here is a clear hint that this might be two stories. I suggest going through all of them and thinking about this, especially in conjunction with #3.

**Comment by sirjdt** [comment]
The wireframe of the inventory shows page numbers to imply that the program lets users view a few items at a time or give them the option to view all the items on a single page.

**Comment by pjohnmeyer** [comment]
I see that, but think about it this way. If I split this into two user stories, does each one still individually add value?

"As a user I would like to view all inventory on a single page so I can quickly scan the entire inventory."

"As a user I would like to view the inventory in smaller pages so I can <insert reason here>."

I'm not saying these are the right stories, but when you break them down you make the work smaller and easier to review -- and you might realize you don't even need them both for MVP.
